### ISSUE TITLE
Test suite issue

### ISSUE THREAD

**Issue by tillea** [kkholst/lava#14] opened 2023-11-21 10:45 UTC
Hi,
I intend to upgrade the Debian package if lava.  Unfortunately the testsuite has some failure in our setup.  You can see the [full test log](https://salsa.debian.org/r-pkg-team/r-cran-lava/-/jobs/4906886#L664) which contains:

    == Failed tests ================================================================
    -- Error ('test-model.R:97:5'): Graph attributes -------------------------------
    Error in `testthat::expect_match(col, graph::nodeRenderInfo(g2)$fill[v])`: is.character(regexp) is not TRUE
    Backtrace:
        x
     1. \-testthat::expect_match(col, graph::nodeRenderInfo(g2)$fill[v]) at test-model.R:97:4
     2.   \-base::stopifnot(is.character(regexp), length(regexp) == 1)
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 254 ]

Any idea what might be wrong here?
Kind regards, Andreas.

**Comment by kkholst** [comment] 2023-12-09 10:45
This is strange as that particular unit test has been passing for a long time on various platforms. I suspect it might be related to the graph package from Bioconductor. I am running a newer version on my machine (1.80.0) compared to 1.78.0-1 in your example where I cannot reproduce this error. 
I cleaned up the unit-test as it should not really be string matching a regular expression: [7c6b47e](https://github.com/kkholst/lava/commit/7c6b47e9e1ff5b91f2191e37f985e7172ad0490d) but doubt that this will fix the issue?

**Comment by tillea** [comment] 2023-12-09 17:02
Hi,
thank you for your comments to this issue.
Meanwhile Bioconductor graph is available in its latest version (1.80.0) and I also applied your patch above.  Unfortunately both has no influence on the issue which you can see in [the updated log](https://salsa.debian.org/r-pkg-team/r-cran-lava/-/jobs/5018918#L628).
Any further ideas?  Kind regards, Andreas.

**Comment by kkholst** [comment] 2023-12-10 07:35
I could now reproduce the error in a debian docker container - the error happens when Rgrapviz is not installed
and this is now fixed in c1e26652923af83b3c2de864210044bb8e6aa2d4.
It seems there is no longer a debian package for Rgraphviz?

**Comment by tillea** [comment] 2023-12-10 09:54
Hi Klaus,
Am Sat, Dec 09, 2023 at 11:35:16PM -0800 schrieb Klaus K. Holst:
> I could now reproduce the error in a debian docker container - the error happens when Rgrapviz is not installed
> and this is now fixed in c1e26652923af83b3c2de864210044bb8e6aa2d4.

This patch was helpful and I uploaded the package with this patch.

> It seems there is no longer a debian package for Rgraphviz?

This package was never pacckaged for Debian.  Usually we package some CRAN
packages due to dependencies.  For some of the test-dependencies we also
package something but your solution is more convenient, thought.

Thanks a lot for your support, Andreas.

**Closed** 2023-12-10 19:29 UTC
